import type { Metadata } from "next";
import { Quicksand } from "next/font/google";

// components
import Sidebar from "./components/Sidebar/Sidebar";

// our global stylesheet
import "./globals.css";
import GlobalStyles from "./providers/GlobalStyles";
import ContextProvider from "./providers/ContextProvider";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <ContextProvider>
          <GlobalStyles>
            <Sidebar />
            {children}
          </GlobalStyles>
        </ContextProvider>
      </body>
    </html>
  );
}
